<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MACs-Mac-mini.local" failures="1" tests="2" name="Testcases" time="34.666" errors="0" timestamp="2025-03-28T13:15:41 IST">
  <testcase classname="TestCases.LoginTest" name="Valid_login" time="7.282"/>
  <testcase classname="TestCases.LoginTest" name="invalid_login" time="6.207">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at TestCases.LoginTest.invalid_login(LoginTest.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- invalid_login -->
</testsuite> <!-- Testcases -->
